INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (1, 'Аал', 'аал', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (2, 'Автономный округ', 'АО', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (3, 'Автономная область', 'Аобл', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (4, 'Арбан', 'арбан', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (5, 'Аул', 'аул', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (6, 'Выселки(ок)', 'высел.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (7, 'Город', 'г.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (8, 'Городок', 'городок', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (9, 'городской поселок', 'гп', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (10, 'Деревня', 'д.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (11, 'Дачный поселок', 'дп', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (12, 'Железнодорожная будка', 'ж/д_будка', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (13, 'Железнодорожная казарма', 'ж/д_казарм', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (14, 'ж/д останов. (обгонный) пункт', 'ж/д_оп', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (15, 'Железнодорожная платформа', 'ж/д_платф', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (16, 'Железнодорожный пост', 'ж/д_пост', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (17, 'Железнодорожный разъезд', 'ж/д_рзд', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (18, 'Железнодорожная станция', 'ж/д_ст', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (19, 'Жилая зона', 'жилзона', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (20, 'Жилой район', 'жилрайон', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (21, 'Заимка', 'заимка', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (22, 'Казарма', 'казарма', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (23, 'Квартал', 'кв-л', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (24, 'Кордон', 'кордон', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (25, 'Курортный поселок', 'кп', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (26, 'Край', 'край', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (27, 'Леспромхоз', 'лпх', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (28, 'Местечко', 'м.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (29, 'Массив', 'массив', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (30, 'Микрорайон', 'мкр.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (31, 'Населенный пункт', 'нп', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (32, 'Область', 'обл.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (33, 'Остров', 'остров', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (34, 'Поселок', 'п.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (35, 'Поселение', 'поселение', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (36, 'Поселок и(при) станция(и)', 'п/ст', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (37, 'Поселок городского типа', 'пгт', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (38, 'Починок', 'починок', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (39, 'Промышленная зона', 'промзона', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (40, 'Район', 'р-н', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (41, 'Республика', 'Респ', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (42, 'Разъезд', 'рзд', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (43, 'Рабочий поселок', 'рп', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (44, 'Село', 'с', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (45, 'Сельская администрация', 'с/а', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (46, 'Сельское муницип.образование', 'с/мо', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (47, 'Сельский округ', 'с/о', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (48, 'Сельское поселение', 'с/п', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (49, 'Сельсовет', 'с/с', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (50, 'Слобода', 'сл', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (51, 'Садовое неком-е товарищество', 'снт', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (52, 'Станция', 'ст', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (53, 'Станица', 'ст-ца', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (54, 'Территория', 'тер', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (55, 'Улус', 'у', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (56, 'Хутор', 'х', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (57, 'Дачное неком-е партнерство', 'днп', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (58, 'Территория ДНП', 'тер. ДНП', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (59, 'Территория ДНТ', 'тер. ДНТ', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (60, 'Территория СНТ', 'тер. СНТ', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (61, 'Территория ТСН', 'тер. ТСН', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (83, 'Город федерального значения', 'г.ф.з.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (108, 'Округ', 'округ', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (96, 'Чувашия', 'Чувашия', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (75, 'Внутригородская территория', 'вн.тер. г.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (82, 'Городской округ', 'г.о.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (107, 'Муниципальный район', 'м.р-н', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (77, 'Волость', 'волость', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (70, 'Автодорога', 'автодорога', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (87, 'Железнодорожный блокпост', 'ж/д бл-ст', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (85, 'Железнодорожная ветка', 'ж/д в-ка', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (88, 'Железнодорожный комбинат', 'ж/д к-т', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (89, 'Железнодорожный остановочный пункт', 'ж/д о.п.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (86, 'Железнодорожная площадка', 'ж/д пл-ка', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (98, 'Зимовье', 'зим.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (100, 'Кишлак', 'киш.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (111, 'Поселок при железнодорожной станции', 'п. ж/д ст.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (112, 'Поселок разъезда', 'пос.рзд', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (69, 'Абонентский ящик', 'а/я', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (71, 'Аллея', 'ал.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (72, 'Берег', 'б-г', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (73, 'Бульвар', 'б-р', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (74, 'Вал', 'вал', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (78, 'Въезд', 'взд.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (80, 'Гаражно-строительный кооп.', 'гск', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (84, 'Дорога', 'дор.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (90, 'Заезд', 'ззд.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (99, 'Зона (массив)', 'зона', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (91, 'Километр', 'км', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (102, 'Коса', 'коса', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (101, 'Кольцо', 'к-цо', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (103, 'Линия', 'лн.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (105, 'Местность', 'местность', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (113, 'Промышленный район', 'п/р', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (109, 'Парк', 'парк', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (110, 'Переезд', 'пер-д', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (114, 'Просек', 'пр-к', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (115, 'Просека', 'пр-ка', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (117, 'Проспект', 'пр-кт', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (116, 'Проселок', 'пр-лок', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (118, 'Проулок', 'проул.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (119, 'Сад', 'сад', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (122, 'Спуск', 'с-к', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (121, 'Сквер', 'сквер', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (123, 'Территория ГСК', 'тер. ГСК', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (124, 'Территория ДНО', 'тер. ДНО', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (125, 'Территория ДПК', 'тер. ДПК', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (126, 'Территория ОНО', 'тер. ОНО', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (127, 'Территория ОНП', 'тер. ОНП', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (128, 'Территория ОНТ', 'тер. ОНТ', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (129, 'Территория ОПК', 'тер. ОПК', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (130, 'Территория ПК', 'тер. ПК', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (97, 'Территория СНО', 'тер. СНО', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (131, 'Территория СНП', 'тер. СНП', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (133, 'Территория СПК', 'тер. СПК', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (134, 'Территория ТСЖ', 'тер. ТСЖ', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (132, 'Территория СОСН', 'тер.СОСН', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (92, 'Территория ФХ', 'тер.ф.х.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (93, 'Тракт', 'тракт', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (94, 'Тупик', 'туп.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (95, 'Фермерское хозяйство', 'ф/х', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (67, 'Шоссе', 'ш.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (68, 'Юрты', 'ю.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (81, 'городское поселение', 'г.п.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (76, 'внутригородской район', 'вн.р-н', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (104, 'межселенная территория', 'межсел.тер', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (106, 'Муниципальный округ', 'м.о.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (120, 'Садовое товарищество', 'с/т', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (79, 'Выселки', 'в-ки', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (135, 'Месторождение', 'месторожд.', 0, NULL);
INSERT INTO gar_tmp.adr_area_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (136, 'Набережная', 'наб.', 0, NULL);
--
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (137, 'Сельский поселок', 'сп.', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (138, 'Усадьба', 'ус.', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (139, 'Поселок при станции (поселок станции)', 'п. ст.', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (140, 'Некоммерческое партнерство', 'н/п', 0, NULL);
--
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (141, 'Железнодорожный путевой пост', 'ж/д п.п.', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (142, 'Платформа', 'платф', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (143, 'Порт', 'порт', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (144, 'Погост', 'погост', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (145, 'Планировочный район', 'пл.р-н', 0, NULL);
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (146, 'Почтовое отделение', 'п/о', 0, NULL);
--
INSERT INTO gar_tmp.adr_house_type (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (147, 'Площадка', 'пл-ка', 0, NULL);
