DELETE FROM gar_tmp.xxx_adr_house_type;
--
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{4}', 8, 'Гараж', 'Гараж', 'г-ж', 'г-ж', 1, 'гараж', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{5}', 9, 'Здание', 'Здание', 'зд.', 'зд.', 1, 'здание', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{9}', 10, 'Литера', 'Литера', 'литера', 'литера', 1, 'литера', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{1}', 1, 'Владение', 'Владение', 'влд.', 'вл.', 1, 'владение', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{2}', 2, 'Дом', 'Дом', 'д.', 'д.', 1, 'дом', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{3}', 3, 'Домовладение', 'Домовладение', 'двлд.', 'дв.', 1, 'домовладение', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{10}', 4, 'Корпус', 'Корпус', 'к.', 'корп.', 2, 'корпус', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{7}', 5, 'Строение', 'Строение', 'стр.', 'стр.', 3, 'строение', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES ('{8}', 6, 'Сооружение', 'Сооружение', 'соор.', 'соор.', 3, 'сооружение', false);
INSERT INTO gar_tmp.xxx_adr_house_type (fias_ids, id_house_type, fias_type_name, nm_house_type, fias_type_shortname, nm_house_type_short, kd_house_type_lvl, fias_row_key, is_twin) VALUES (NULL, 7, NULL, 'Литер', NULL, 'литер', 3, 'литер', false);
