DELETE FROM unnsi.adr_area;
--
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (1, 'Аал', 'аал', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (2, 'Автономный округ', 'АО', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (3, 'Автономная область', 'Аобл', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (4, 'Арбан', 'арбан', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (5, 'Аул', 'аул', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (6, 'Выселки(ок)', 'высел.', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (7, 'Город', 'г.', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (8, 'Городок', 'городок', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (9, 'городской поселок', 'гп', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (10, 'Деревня', 'д.', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (11, 'Дачный поселок', 'дп', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (12, 'Железнодорожная будка', 'ж/д_будка', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (13, 'Железнодорожная казарма', 'ж/д_казарм', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (14, 'ж/д останов. (обгонный) пункт', 'ж/д_оп', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (15, 'Железнодорожная платформа', 'ж/д_платф', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (16, 'Железнодорожный пост', 'ж/д_пост', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (17, 'Железнодорожный разъезд', 'ж/д_рзд', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (18, 'Железнодорожная станция', 'ж/д_ст', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (19, 'Жилая зона', 'жилзона', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (20, 'Жилой район', 'жилрайон', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (21, 'Заимка', 'заимка', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (22, 'Казарма', 'казарма', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (23, 'Квартал', 'кв-л', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (24, 'Кордон', 'кордон', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (25, 'Курортный поселок', 'кп', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (26, 'Край', 'край', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (27, 'Леспромхоз', 'лпх', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (28, 'Местечко', 'м.', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (29, 'Массив', 'массив', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (30, 'Микрорайон', 'мкр.', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (31, 'Населенный пункт', 'нп', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (32, 'Область', 'обл.', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (33, 'Остров', 'остров', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (34, 'Поселок', 'п.', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (35, 'Поселение', 'поселение', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (36, 'Поселок и(при) станция(и)', 'п/ст', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (37, 'Поселок городского типа', 'пгт', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (38, 'Починок', 'починок', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (39, 'Промышленная зона', 'промзона', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (40, 'Район', 'р-н', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (41, 'Республика', 'Респ', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (42, 'Разъезд', 'рзд', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (43, 'Рабочий поселок', 'рп', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (44, 'Село', 'с', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (45, 'Сельская администрация', 'с/а', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (46, 'Сельское муницип.образование', 'с/мо', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (47, 'Сельский округ', 'с/о', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (48, 'Сельское поселение', 'с/п', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (49, 'Сельсовет', 'с/с', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (50, 'Слобода', 'сл', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (51, 'Садовое неком-е товарищество', 'снт', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (52, 'Станция', 'ст', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (53, 'Станица', 'ст-ца', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (54, 'Территория', 'тер', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (55, 'Улус', 'у', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (56, 'Хутор', 'х', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (57, 'Дачное неком-е партнерство', 'днп', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (58, 'Территория ДНП', 'тер. ДНП', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (59, 'Территория ДНТ', 'тер. ДНТ', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (60, 'Территория СНТ', 'тер. СНТ', 0, NULL);
INSERT INTO unnsi.adr_area (id_area_type, nm_area_type, nm_area_type_short, pr_lead, dt_data_del) VALUES (61, 'Территория ТСН', 'тер. ТСН', 0, NULL);
