/*==============================================================*/
/* DBMS name:      PostgreSQL 13.12    2024-03-01               */
/*==============================================================*/
GRANT USAGE ON SCHEMA clientdb TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA clientdb
 GRANT ALL ON TABLES TO mb_owner_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA clientdb
 GRANT SELECT ON TABLES TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA clientdb
 GRANT ALL ON SEQUENCES TO mb_owner_04;
--  
-- 
--
GRANT USAGE ON SCHEMA contacts TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
 GRANT ALL ON TABLES TO mb_owner_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
 GRANT SELECT ON TABLES TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
 GRANT ALL ON SEQUENCES TO mb_owner_04;
--  
--  
--  
GRANT USAGE ON SCHEMA metamodel TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA metamodel
 GRANT ALL ON TABLES TO mb_owner_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA metamodel
 GRANT SELECT ON TABLES TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA metamodel
 GRANT ALL ON SEQUENCES TO mb_owner_04;
--  
--
--
GRANT USAGE ON SCHEMA dict TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
 GRANT ALL ON TABLES TO mb_owner_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
 GRANT SELECT ON TABLES TO mb_reader_04;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
 GRANT ALL ON SEQUENCES TO mb_owner_04;
  
