/*==============================================================*/
/* DBMS name:      PostgreSQL 13.12  2024-02-29                 */
/*==============================================================*/
-- DROP ROLE mb_reader;
-- CREATE ROLE mb_reader WITH
--   LOGIN
--   NOSUPERUSER
--   INHERIT
--   NOCREATEDB
--   NOCREATEROLE
--   NOREPLICATION
--   CONNECTION LIMIT 2
--   VALID UNTIL 'infinity';
--  
-- DROP ROLE mb_owner;
-- CREATE ROLE mb_owner WITH
--   LOGIN
--   NOSUPERUSER
--   INHERIT
--   NOCREATEDB
--   NOCREATEROLE
--   NOREPLICATION
--   CONNECTION LIMIT 2
--   VALID UNTIL 'infinity';

--
--  Пробуем так.
--

CREATE ROLE mb_reader_01 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
 
CREATE ROLE mb_owner_01 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
  
CREATE ROLE mb_reader_02 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
 
CREATE ROLE mb_owner_02 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
  
CREATE ROLE mb_reader_03 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
 
CREATE ROLE mb_owner_03 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
  
CREATE ROLE mb_reader_04 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
 
CREATE ROLE mb_owner_04 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
  
CREATE ROLE mb_reader_05 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity'
 
CREATE ROLE mb_owner_05 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  CONNECTION LIMIT 2
  VALID UNTIL 'infinity';
  
