CREATE SCHEMA IF NOT EXISTS dict
    AUTHORIZATION mb_owner;

GRANT ALL ON SCHEMA dict TO mb_owner;

GRANT USAGE ON SCHEMA dict TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
GRANT ALL ON TABLES TO mb_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
GRANT SELECT ON TABLES TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
GRANT ALL ON SEQUENCES TO mb_owner;
