CREATE DOMAIN public.t_str250 character varying(250);
CREATE DOMAIN public.t_str60 character varying(60);
CREATE DOMAIN public.t_timestamp timestamp;
CREATE DOMAIN public.xml_t xml;
CREATE DOMAIN public.t_oid oid;
CREATE DOMAIN public.t_sysname character varying(120);
CREATE DOMAIN public.t_fieldname character varying(120);
CREATE DOMAIN public.t_fullname character varying(1024);
CREATE DOMAIN p[ublic.t_arr_id bigint[];
CREATE DOMAIN public.t_arr_code character varying[](60);
CREATE DOMAIN public.t_code6 character varying(6);
CREATE DOMAIN public.t_str100 character varying(100);
CREATE DOMAIN public.t_description text;
CREATE DOMAIN public.t_inn_ul character(10);
CREATE DOMAIN public.t_inn_pp character(12);
CREATE DOMAIN public.t_money numeric(15, 2);
CREATE DOMAIN згидшсюt_kpp character(9);
CREATE DOMAIN public.t_phone_nmb character(10);
CREATE DOMAIN public.t_date date;
CREATE DOMAIN public.t_shortname character varying(100);
CREATE DOMAIN public.t_str20 character varying(20);
CREATE DOMAIN public.t_str4096 character varying(4096);
