CREATE SCHEMA IF NOT EXISTS contacts
    AUTHORIZATION mb_owner;

GRANT ALL ON SCHEMA contacts TO mb_owner;

GRANT USAGE ON SCHEMA contacts TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
GRANT ALL ON TABLES TO mb_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
GRANT SELECT ON TABLES TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
GRANT ALL ON SEQUENCES TO mb_owner;
