CREATE SCHEMA IF NOT EXISTS metamodel
    AUTHORIZATION mb_owner;

GRANT ALL ON SCHEMA metamodel TO mb_owner;

GRANT USAGE ON SCHEMA metamodel TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA metamodel
GRANT ALL ON TABLES TO mb_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA metamodel
GRANT SELECT ON TABLES TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA metamodel
GRANT ALL ON SEQUENCES TO mb_owner;


CREATE SCHEMA IF NOT EXISTS dict
    AUTHORIZATION mb_owner;

GRANT ALL ON SCHEMA dict TO mb_owner;

GRANT USAGE ON SCHEMA dict TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
GRANT ALL ON TABLES TO mb_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
GRANT SELECT ON TABLES TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA dict
GRANT ALL ON SEQUENCES TO mb_owner;


CREATE SCHEMA IF NOT EXISTS clientdb
    AUTHORIZATION mb_owner;

GRANT ALL ON SCHEMA clientdb TO mb_owner;

GRANT USAGE ON SCHEMA clientdb TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA clientdb
GRANT ALL ON TABLES TO mb_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA clientdb
GRANT SELECT ON TABLES TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA clientdb
GRANT ALL ON SEQUENCES TO mb_owner;


CREATE SCHEMA IF NOT EXISTS contacts
    AUTHORIZATION mb_owner;

GRANT ALL ON SCHEMA contacts TO mb_owner;

GRANT USAGE ON SCHEMA contacts TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
GRANT ALL ON TABLES TO mb_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
GRANT SELECT ON TABLES TO mb_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA contacts
GRANT ALL ON SEQUENCES TO mb_owner;
