DELETE FROM gar_tmp.xxx_adr_street_type;
--
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{114,115}', 1, 'Аллея', 'Аллея', 'ал.', 'аллея', 'аллея', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{118}', 2, 'Бульвар', 'Бульвар', 'б-р', 'б-р', 'бульвар', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{116}', 3, 'Балка', 'Балка', 'балка', 'балка', 'балка', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES (NULL, 6, NULL, 'Бухта', NULL, 'бухта', 'бухта', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{117}', 4, 'Берег', 'Берег', 'берег', 'берег', 'берег', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{119}', 5, 'Бугор', 'Бугор', 'бугор', 'бугор', 'бугор', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{120}', 7, 'Вал', 'Вал', 'вал', 'вал', 'вал', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{122}', 8, 'Въезд', 'Въезд', 'въезд', 'въезд', 'въезд', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{136,137}', 9, 'Заезд', 'Заезд', 'заезд', 'заезд', 'заезд', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{138}', 10, 'Зона', 'Зона', 'зона', 'зона', 'зона', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES (NULL, 11, NULL, 'Канал', NULL, 'канал', 'канал', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{140}', 12, 'Квартал', 'Квартал', 'кв-л', 'кв-л', 'квартал', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{142,144}', 13, 'Кольцо', 'Кольцо', 'кольцо', 'кольцо', 'кольцо', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{143}', 14, 'Коса', 'Коса', 'коса', 'коса', 'коса', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{145,146}', 15, 'Линия', 'Линия', 'линия', 'линия', 'линия', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{151}', 16, 'Микрорайон', 'Микрорайон', 'мкр', 'мкр.', 'микрорайон', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{154,155}', 17, 'Набережная', 'Набережная', 'наб', 'наб.', 'набережная', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{162}', 18, 'Парк', 'Парк', 'парк', 'парк', 'парк', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{163,164}', 19, 'Переулок', 'Переулок', 'пер', 'пер.', 'переулок', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{165,166}', 20, 'Переезд', 'Переезд', 'пер-д', 'переезд', 'переезд', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{167,450}', 21, 'Площадь', 'Площадь', 'пл', 'пл.', 'площадь', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{174}', 22, 'Проспект', 'Проспект', 'пр-кт', 'пр-кт', 'проспект', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{171,176}', 23, 'Проезд', 'Проезд', 'пр-д', 'проезд', 'проезд', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{172,178}', 24, 'Просек', 'Просек', 'пр-к', 'просек', 'просек', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{173,179}', 25, 'Просека', 'Просека', 'пр-ка', 'просека', 'просека', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES (NULL, 26, NULL, 'Проток', NULL, 'проток', 'проток', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{181,182}', 27, 'Проулок', 'Проулок', 'проул.', 'проулок', 'проулок', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{183,184}', 28, 'Разъезд', 'Разъезд', 'рзд', 'рзд', 'разъезд', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{189}', 30, 'Сад', 'Сад', 'сад', 'сад', 'сад', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{192,196}', 31, 'Сквер', 'Сквер', 'сквер', 'сквер', 'сквер', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{191,195}', 32, 'Спуск', 'Спуск', 'с-к', 'спуск', 'спуск', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{197}', 33, 'Станция', 'Станция', 'ст', 'ст.', 'станция', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{199}', 34, 'Территория', 'Территория', 'тер', 'тер.', 'территория', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES (NULL, 35, NULL, 'тоннель', NULL, 'тоннель', 'тоннель', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{202}', 36, 'Тракт', 'Тракт', 'тракт', 'тракт', 'тракт', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{203,451}', 37, 'Тупик', 'Тупик', 'туп', 'туп.', 'тупик', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{204,205}', 38, 'Улица', 'Улица', 'ул', 'ул.', 'улица', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{206}', 39, 'Участок', 'Участок', 'уч-к', 'уч-к', 'участок', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{210,211}', 40, 'Шоссе', 'Шоссе', 'ш', 'ш.', 'шоссе', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{168}', 41, 'Платформа', 'Платформа', 'платф', 'платф.', 'платформа', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{141}', 42, 'Километр', 'Километр', 'км', 'км.', 'километр', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{123}', 43, 'Городок', 'Городок', 'г-к', 'г-к', 'городок', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{124}', 44, 'Гаражно-строительный кооп.', 'Гаражно-строительный кооп.', 'гск', 'гск', 'гаражностроительныйкооп', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{139}', 45, 'Казарма', 'Казарма', 'казарма', 'казарма', 'казарма', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{147}', 46, 'Местечко', 'Местечко', 'м', 'м', 'местечко', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{157}', 47, 'Остров', 'Остров', 'остров', 'остров', 'остров', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES (NULL, 48, NULL, 'Ряд', NULL, 'ряд', 'ряд', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{126}', 49, 'Дачное неком-е партнерство', 'Дачное неком-е партнерство', 'днп', 'днп', 'дачноенекомепартнерство', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{127}', 50, 'Дорога', 'Дорога', 'дор', 'дор', 'дорога', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{148}', 51, 'Маяк', 'Маяк', 'маяк', 'маяк', 'маяк', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{149}', 52, 'Магистраль', 'Магистраль', 'мгстр.', 'мгстр.', 'магистраль', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{153}', 53, 'Некоммерческое партнерство', 'Некоммерческое партнерство', 'н/п', 'н/п', 'некоммерческоепартнерство', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{160}', 54, 'Планировочный район', 'Планировочный район', 'пл.р-н', 'пл.р-н', 'планировочныйрайон', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{170}', 55, 'Полустанок', 'Полустанок', 'полустанок', 'полустанок', 'полустанок', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{200}', 56, 'Территория ДНТ', 'Территория ДНТ', 'тер. ДНТ', 'тер. ДНТ', 'территорияднт', false);
INSERT INTO gar_tmp.xxx_adr_street_type (fias_ids, id_street_type, fias_type_name, nm_street_type, fias_type_shortname, nm_street_type_short, fias_row_key, is_twin) VALUES ('{186,185,397}', 29, 'Ряды', 'Ряды', 'ряды', 'ряды', 'ряды', false);


-- Completed on 2023-01-08 18:26:37 MSK

--
-- PostgreSQL database dump complete
--

